### ISSUE TITLE
Support multi-valued defaults for table-like data

### ISSUE THREAD

**Issue by emolter** [spacetelescope/stdatamodels#468]
Related to https://github.com/spacetelescope/stdatamodels/pull/466, there was a request to change the default values of some of the columns in a table to NaN.

Imagine the schema for the data table looks like
```
%YAML 1.1
---
$schema: "http://stsci.edu/schemas/asdf/asdf-schema-1.1.0"
id: "http://stsci.edu/schemas/jwst_datamodel/wfss_spectable.schema"
title: Extracted spectral data table
fits_hdu: EXTRACT1D
default: 0.0
datatype:
- name: WAVELENGTH
  datatype: float64
- name: DQ
  datatype: uint32
- name: NAME
  datatype: [ascii, 20]
```
which is a slimmed-down version of what we need for https://github.com/spacetelescope/jwst/issues/9282.  Now call
```
import stdatamodels.jwst.datamodels as dm
model = dm.WFSSMultiSpecModel((50,))
print(model.spec_table["WAVELENGTH"]) # returns array of zero-valued float64
print(model.spec_table["DQ"]) # returns array of zero-valued int
print(model.spec_table["NAME"]) # returns array of byte strings b'0.0'
```

The desired behavior would be that the wavelength column could default to an array of NaNs, the DQ column could default to zero, and the name column could default to an empty string.  However, it appears there's no way to make this happen at present, because `stdatamodels.properties._make_default_array()` cannot handle a multi-valued data type, and (AFAIK) there's no way to define a default for each column.

Possible solutions would be:

- Handle parsing multi-valued datatypes in `_make_default_array`.  It appears there are no issues loading an arbitrarily complex datatype value from the schema, it just ends up as a string.  So we could e.g. check if the datatype field looks like a dict (or list) and handle it from there.
- Make it easier for individual datamodel classes to override `_make_default_array()`.  Right now it's a helper function to `getattr` and not directly accessible via e.g. `super()._make_default_array()`

Maybe there are also easier ways to handle this that I'm missing.
